name: repo-pushed
on:
  push:
    paths-ignore:
    - '.github/workflows/**'
    - '.github/m-rec/**'
jobs:
  issue-edited:
    runs-on: ubuntu-latest
    name: Send to Slack workflow When Pushed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make Message
        id: make-message
        run: |
          echo '${{ secrets.REPO_PUSHED_SLACK_MENTION }}' >> tmp
          echo '${{ github.server_url }}/${{ github.repository }}' >> tmp
          echo 'pushされました' >> tmp

          # JSON形式テキストに変換してOUTPUTに出力
          echo "message=$(cat tmp | tr -d '\r' | jq -Rs .)" >> $GITHUB_OUTPUT

      - name: Send to Slack workflow
        id: edited-slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": ${{ steps.make-message.outputs.message }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.REPO_PUSHED_SLACK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
